name: Publish
on:
  release:
    types: [ published ]

jobs:
  publish-google-play:
    uses: ./.github/workflows/publish-google-play.yml
    secrets: inherit

  publish-fdroid-tag:
    needs: publish-google-play
    uses: ./.github/workflows/publish-fdroid-tag.yml
    secrets: inherit
    with:
      release_tag: ${{ github.event.release.tag_name }}

  publish-snap:
    needs: publish-google-play
    uses: ./.github/workflows/publish-snap.yml
    secrets: inherit
    with:
      release_tag: ${{ github.event.release.tag_name }}

  publish-microsoft-store:
    needs: publish-google-play
    uses: ./.github/workflows/publish-microsoft-store.yml
    secrets: inherit

  publish-mac-app-store:
    uses: ./.github/workflows/publish-mac-app-store.yml
    secrets: inherit

  publish-ios-app-store:
    uses: ./.github/workflows/publish-ios-app-store.yml
    secrets: inherit

  notify:
    needs: [ publish-fdroid-tag, publish-google-play, publish-snap, publish-microsoft-store, publish-mac-app-store, publish-ios-app-store ]
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554 # 0.4.0
        with:
          args: "**New release:** {{ EVENT_PAYLOAD.release.name }}\n**Download Here:** {{ EVENT_PAYLOAD.release.html_url }}\n\n**Changelog:**\n{{ EVENT_PAYLOAD.release.body }}"
