-- Authoritative snapshot of the PostgreSQL schema as a FRESH v1 install
-- produced it: the version-1 CREATE TABLE / CREATE INDEX statements followed by
-- the type-promotion ALTERs that PostgresSchemaInitializer ran on first boot.
--
-- This is an immutable historical artifact, the analog of SqlDelight's per-
-- version .db schema snapshots. It is the "upgrade-from" baseline for the
-- migration test suite: applying it and then running Schema.migrate(...) forward
-- must reproduce a current fresh install (PostgresMigrationSchemaParityTest), and
-- data seeded against it must survive the upgrade (PostgresMigrationDataCarryForwardTest).
--
-- DO NOT edit this file to follow later schema changes. v1 shipped exactly once.
-- New schema versions add their own .sqm migrations; the tests pick them up via
-- ServerDatabase.Schema.version automatically.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE account(
    id BIGSERIAL PRIMARY KEY,
    email TEXT NOT NULL,
    pen_name TEXT,
    password_hash TEXT NOT NULL,
    cipher_secret TEXT NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    last_sync TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    bio TEXT,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    community_member BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT account_email_shape CHECK (email LIKE '%@%.%'),
    CONSTRAINT account_bio_len CHECK (bio IS NULL OR length(bio) <= 10000),
    CONSTRAINT account_pen_name_len CHECK (pen_name IS NULL OR length(pen_name) BETWEEN 1 AND 64)
);

CREATE UNIQUE INDEX account_email_unique ON account (email);
CREATE UNIQUE INDEX account_pen_name_unique ON account (pen_name) WHERE pen_name IS NOT NULL;
CREATE INDEX account_community_idx ON account (id) WHERE community_member = TRUE;

CREATE TABLE project (
    id BIGSERIAL PRIMARY KEY,
    uuid TEXT NOT NULL,
    user_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    last_id BIGINT NOT NULL DEFAULT 0,
    last_sync TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT project_name_len CHECK (length(name) BETWEEN 1 AND 200),
    FOREIGN KEY(user_id) REFERENCES account(id) ON DELETE CASCADE,
    UNIQUE(name, user_id)
);

CREATE UNIQUE INDEX project_uuid_unique ON project (uuid);
CREATE UNIQUE INDEX user_project_name_lookup ON project (user_id, name);
CREATE INDEX project_user_id_idx ON project (user_id);

CREATE TABLE story_entity (
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    id BIGINT NOT NULL,
    type TEXT NOT NULL,
    content TEXT NOT NULL,
    hash TEXT NOT NULL,
    cipher TEXT,
    CONSTRAINT story_entity_content_max CHECK (length(content) <= 67108864),
    FOREIGN KEY(user_id) REFERENCES account(id) ON DELETE CASCADE,
    FOREIGN KEY(project_id) REFERENCES project(id) ON DELETE CASCADE,
    UNIQUE(user_id, project_id, id)
);

CREATE INDEX entity_def_by_type ON story_entity (user_id, project_id, type);
CREATE INDEX story_entity_pagination ON story_entity (project_id, id);

CREATE TABLE project_data (
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    hash TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY(user_id, project_id),
    FOREIGN KEY(user_id) REFERENCES account(id) ON DELETE CASCADE,
    FOREIGN KEY(project_id) REFERENCES project(id) ON DELETE CASCADE
);

CREATE INDEX project_data_project_id_idx ON project_data (project_id);

CREATE TABLE project_access (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL,
    access_password TEXT,
    expires_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT project_access_expires_after_published CHECK (expires_at IS NULL OR expires_at > published_at),
    FOREIGN KEY(project_id) REFERENCES project(id) ON DELETE CASCADE
);

CREATE INDEX idx_project_access_project_id ON project_access (project_id);
CREATE INDEX idx_project_access_active_expires ON project_access (expires_at) WHERE expires_at IS NOT NULL;

CREATE TABLE auth_token(
    user_id BIGINT NOT NULL,
    install_id TEXT NOT NULL,
    token TEXT NOT NULL,
    refresh TEXT NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, install_id),
    CONSTRAINT auth_token_expires_after_created CHECK (expires > created),
    FOREIGN KEY(user_id) REFERENCES account(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX auth_token_token_unique ON auth_token (token);
CREATE INDEX auth_token_user_id_idx ON auth_token (user_id);
CREATE INDEX auth_token_expires_idx ON auth_token (expires);

CREATE TABLE password_reset_token(
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token TEXT NOT NULL UNIQUE,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires TIMESTAMPTZ NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT password_reset_expires_after_created CHECK (expires > created),
    FOREIGN KEY(user_id) REFERENCES account(id) ON DELETE CASCADE
);

CREATE INDEX password_reset_token_lookup ON password_reset_token (token);
CREATE INDEX password_reset_token_user_id_idx ON password_reset_token (user_id);
CREATE INDEX password_reset_token_expires_idx ON password_reset_token (expires);

CREATE TABLE deleted_project (
    user_id BIGINT NOT NULL,
    uuid TEXT NOT NULL,
    deleted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY(user_id) REFERENCES account(id) ON DELETE CASCADE
);

CREATE INDEX deleted_project_user_id_idx ON deleted_project (user_id);

CREATE TABLE deleted_entity (
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    entity_id BIGINT NOT NULL,
    deleted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY(project_id) REFERENCES project(id) ON DELETE CASCADE,
    UNIQUE(user_id, project_id, entity_id)
);

CREATE INDEX deleted_entity_lookup_all ON deleted_entity (user_id, project_id);
CREATE UNIQUE INDEX deleted_entity_lookup ON deleted_entity (user_id, project_id, entity_id);

CREATE TABLE white_list(
    email TEXT NOT NULL PRIMARY KEY,
    date_added TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reason TEXT DEFAULT ''
);

CREATE TABLE server_config (
    key TEXT NOT NULL PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE writing_activity (
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    device_id TEXT NOT NULL CHECK (device_id != ''),
    content TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES account(id) ON DELETE CASCADE,
    FOREIGN KEY(project_id) REFERENCES project(id) ON DELETE CASCADE,
    UNIQUE(user_id, project_id, device_id)
);

CREATE INDEX writing_activity_user_project_idx ON writing_activity (user_id, project_id);

-- Type promotions PostgresSchemaInitializer applies after Schema.create on first boot.
ALTER TABLE account ALTER COLUMN email TYPE CITEXT;
ALTER TABLE account ALTER COLUMN pen_name TYPE CITEXT;
ALTER TABLE white_list ALTER COLUMN email TYPE CITEXT;
ALTER TABLE project ALTER COLUMN name TYPE CITEXT;
ALTER TABLE project ALTER COLUMN uuid TYPE UUID USING uuid::uuid;
ALTER TABLE deleted_project ALTER COLUMN uuid TYPE UUID USING uuid::uuid;
